from torch_algorithms.policies.model import HybridPolicy
from torch_algorithms.policies.attention_model import MultiDiscreteAttentionPolicy
from torch_algorithms.policies.cnn_model import CNNPolicy
from torch_algorithms.policies.mlp_model import MLPPolicy
